
CREATE TABLE MANAGERLOG
(
    ID     NVARCHAR2 (36) PRIMARY KEY  NOT NULL,
    ACTIONTYPE NVARCHAR2(36) NOT NULL,
    ADDMANAGERID NVARCHAR2(100) NOT NULL,
    ADDMANAGERNICKNAME NVARCHAR2(50) ,
    ADDTIME DATE ,
    ADDIP NVARCHAR2(36) ,
    SORTCODE       NUMBER (20),
    ENABLED        NUMBER (1) DEFAULT (1) NOT NULL,
    CREATEDATE     DATE NOT NULL,
    CREATEUSERID   VARCHAR2 (36) NOT NULL,
    CREATEUSERNAME NVARCHAR2 (36) NOT NULL,
    MODIFYDATE     DATE,
    MODIFYUSERID   VARCHAR2 (36),
    MODIFYUSERNAME NVARCHAR2 (36),
    REMARK         VARCHAR2 (100)
);
--添加表注释：
COMMENT ON TABLE MANAGERLOG IS '操作日志表单';
--添加字段注释

COMMENT ON COLUMN MANAGERLOG.ACTIONTYPE IS '操作类型'; 
COMMENT ON COLUMN MANAGERLOG.ADDMANAGERID IS '添加人ID'; 
COMMENT ON COLUMN MANAGERLOG.ADDMANAGERNICKNAME IS '添加人昵称'; 
COMMENT ON COLUMN MANAGERLOG.ADDTIME IS '添加时间'; 
COMMENT ON COLUMN MANAGERLOG.ADDIP IS '操作电脑IP'; 